version: '3'

services:
  evm-1:
    image: ghcr.io/sygmaprotocol/sygma-solidity:evm1-v1.1.1
    container_name: evm1-1
    command: ganache-cli --chainId 1337 -d --db data/ --blockTime 2 > /dev/null
    logging:
      driver: none
    ports:
      - "8545:8545"

  substrate-pallet-1:
    container_name: substrate-pallet-1
    image: "ghcr.io/sygmaprotocol/sygma-substrate-pallets:latest"
    command: --dev --ws-external
    ports:
      - "9944:9944"