[workspace]
resolver = "2"

members = [
    "access-segregator",
    "basic-fee-handler",
    "bridge",
    "fee-handler-router",
    "traits",
    "runtime-api",
    "rpc",
    "substrate-node/node",
    "substrate-node/runtime",
]

exclude = [

]

[profile.release]
panic = "unwind"
