[workspace]
resolver = "2"

members = [
    "access-segregator",
    "basic-fee-handler",
    "bridge",
    "fee-handler-router",
    "traits",
    "runtime-api",
    "substrate-node/node",
    "substrate-node/runtime",
]

exclude = [

]

[profile.release]
panic = "unwind"

[patch.crates-io]
eth-encode-packed = { git = "https://github.com/tolak/eth-encode-packed-rs.git", branch = "0.1.0-etherabi-18" }
