[settings]
node_spawn_timeout = 240

[relaychain]
default_command = "./polkadot"
default_args = [ "-lparachain=debug,xcm=trace" ]
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice-validator"
	validator = true
	rpc_port = 9932
	ws_port = 9942
	extra_args = ["--no-mdns --bootnodes {{'bob-validator'|zombie('multiAddress')}}"]

	[[relaychain.nodes]]
	name = "bob-validator"
	validator = true
	rpc_port = 9933
	ws_port = 9943
	extra_args = ["--no-mdns --bootnodes {{'alice-validator'|zombie('multiAddress')}}"]

[[parachains]]
id = 1013
chain = "bridge-hub-rococo-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "bridge-hub-alice-collator"
	validator = true
	command = "./polkadot-parachain"
	rpc_port = 8933
	ws_port = 8943
	args = [
		"-lparachain=debug,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm=trace",
	]
	extra_args = [
		"--force-authoring", "--no-mdns", "--bootnodes {{'bridge-hub-bob-collator'|zombie('multiAddress')}}",
		"-- --port 41333 --rpc-port 48933 --ws-port 48943 --no-mdns", "--bootnodes {{'alice-validator'|zombie('multiAddress')}}"
	]

	# run bob as parachain collator
	[[parachains.collators]]
	name = "bridge-hub-bob-collator"
	validator = true
	command = "./polkadot-parachain"
	rpc_port = 8934
	ws_port = 8944
	args = [
		"-lparachain=trace,runtime::bridge-hub=trace,runtime::bridge=trace,runtime::bridge-dispatch=trace,bridge=trace,runtime::bridge-messages=trace,xcm=trace",
	]
	extra_args = [
		"--force-authoring", "--no-mdns", "--bootnodes {{'bridge-hub-alice-collator'|zombie('multiAddress')}}",
		"-- --port 41334 --rpc-port 48934 --ws-port 48944 --no-mdns", "--bootnodes {{'bob-validator'|zombie('multiAddress')}}"
	]

[[parachains]]
id = 1000
chain = "asset-hub-kusama-local"
cumulus_based = true

	[[parachains.collators]]
	name = "asset-hub-alice-collator"
	rpc_port = 9911
	ws_port = 9910
	command = "./polkadot-parachain"
	args = [
		"-lparachain=debug,xcm=trace,runtime::bridge-transfer=trace",
	]
	extra_args = [
		"--no-mdns", "--bootnodes {{'asset-hub-bob-collator'|zombie('multiAddress')}}",
		"-- --port 51333 --rpc-port 58933 --ws-port 58943 --no-mdns", "--bootnodes {{'alice-validator'|zombie('multiAddress')}}"
	]

	[[parachains.collators]]
	name = "asset-hub-bob-collator"
	command = "./polkadot-parachain"
	args = [
		"-lparachain=debug,xcm=trace,runtime::bridge-transfer=trace",
	]
	extra_args = [
		"--no-mdns", "--bootnodes {{'asset-hub-alice-collator'|zombie('multiAddress')}}",
		"-- --port 51433 --rpc-port 58833 --ws-port 58843 --no-mdns", "--bootnodes {{'alice-validator'|zombie('multiAddress')}}"
	]

[[hrmp_channels]]
sender = 1000
recipient = 1013
max_capacity = 4
max_message_size = 524288

[[hrmp_channels]]
sender = 1013
recipient = 1000
max_capacity = 4
max_message_size = 524288
