# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

name: Build and publish Subbridge E2E Docker image

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_subbridge_e2e_to_registry:
    name: Push Phala subbridge integrated E2E Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_toolchain

      - name: Prepare
        id: prep
        run: |
          # creates local variable of docker image

          # creates local variable of commit hash that triggered workflow
          COMMIT_HASH=$(echo $GITHUB_SHA | head -c7)

          # creates local variable to hold docker images
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${COMMIT_HASH},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:subbridge-e2e-latest"

          # check if branch/tag that triggered workflow was from tags
          if [[ $GITHUB_REF == refs/tags/* ]]; then

            # set version
            VERSION=${GITHUB_REF#refs/tags/}

            # append version and e2e testing name to tags
            TAGS="${TAGS},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:subbridge-e2e-${VERSION}"

          fi

          # sets output of step
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile_subbridge_e2e_remote
          tags: ${{ steps.prep.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
